### ISSUE TITLE
如何分别设置输入图片IMAGE_SIZE的长宽?

### ISSUE THREAD

**Issue by ZhanJunxiang** [yatengLG/Retinanet-Pytorch#13]
感谢提供此代码！但由于原本设置的是将输入图像的长宽都resize到同一IMAGE_SIZE大小(600px)，但对于像KITTI这样长宽比悬殊的数据集，原图长宽比大约为1200*375左右，若resize到同一大小，就将导致行人/自行车到目标的像素严重缺失，无法识别。因此我希望能分别设置IMAGE_SIZE的width和height，请问这样的话，对于anchor和feature map大小，以及内部一系列参数的设置该如何修改？

**Comment by yatengLG** [comment]
你需要手动调整模型，中图片的resize尺寸，因为我这里直接写成了，宽高相同的。你需要手动修改下

然后，模型结构中，不需要调整太多，但是由于输入变了，所以特征图尺寸需要修改，这部分需要你自己计算下对应的特征图尺寸是多少。

anchor的话，需要你自己定了，因为不同数据集目标尺寸不一样的，你可以对数据集中目标进行一个统计，然后计算得出一个比较合适的anchor尺寸。

如果我没有记错的话，数据增里面也有需要改动的地方，这部分自己找找。

------------------------------------------------------------------------
另外，很抱歉，现在才回你，之前有事一直没空，望见谅。
